### PR TITLE
Format code sample in explainer/modes.md

### PR DESCRIPTION
**Pull request by dmcardle**

### CODE REVIEW

**Comment by dmcardle** [comment]
@shivanigithub PTAL :)

**Comment by dmcardle** [comment]
Just sent a request to join. Thanks!

**Comment by dmcardle** [comment]
Alternatively, I guess you could mark this as a non-substantive change. It's really just formatting, after all.

**Review by shivanigithub — APPROVED** [review]

**Comment by dmcardle** [comment]
Thanks, Shivani! I think I need someone to "approve and run" the workflow before this can be merged.

**Pull request merged**
